sudo: required
services:
  - docker

before_install: 
  - docker build -t fouedkrichene/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fouedkrichene/udemy-docker-react npm run test