# Specify base image
FROM node:20-alpine

# Install some dependencies
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY . .

# Default command
CMD ["npm", "run", "start"]

# FROM node:lts-alpine
# ENV NODE_ENV=production
# WORKDIR /usr/src/app
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# RUN npm install --production --silent && mv node_modules ../
# COPY . .
# EXPOSE 3000
# RUN chown -R node /usr/src/app
# USER node
# CMD ["npm", "start"]
